if(CMAKE_SYSTEM_PROCESSOR MATCHES "AMD64|x86_64")
    set(ARCH "x64")
    message(STATUS "Detected architecture: x64")
elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "x86|i686")
    set(ARCH "x86")
    message(STATUS "Detected architecture: x86")
elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "ARM64")
    set(ARCH "arm64")
    message(STATUS "Detected architecture: ARM64")
else()
    message(FATAL_ERROR "Unsupported architecture: ${CMAKE_SYSTEM_PROCESSOR}")
endif()